// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApi.Data;

#nullable disable

namespace TaskManagerApi.Migrations
{
    [DbContext(typeof(TaskItemDbContext))]
    partial class TaskItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("TaskManagerApi.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 1,
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            Status = 0,
                            Title = "Build REST API"
                        },
                        new
                        {
                            Id = 3,
                            Status = 2,
                            Title = "Add Database"
                        },
                        new
                        {
                            Id = 4,
                            Status = 0,
                            Title = "Deploy Application"
                        },
                        new
                        {
                            Id = 5,
                            Status = 3,
                            Title = "Write Tests"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
